### ISSUE TITLE
New bs-preloaded causes fatals on a few sites

### ISSUE THREAD

**Issue by andresanz** [bootscore/bs-preloader#17]
GM - have disabled for now, but the new bs-preloader causes the following error on several of my sites

> Fatal error: Uncaught Error: Class "Puc_v4_Factory" not found in /mnt/volume01/www/html/stuffandrewrites.com/public_html/wp-content/plugins/bs-preloader-main/main.php:21 Stack trace: #0 /mnt/volume01/www/html/stuffandrewrites.com/public_html/wp-admin/includes/plugin.php(2318): include_once() #1 /mnt/volume01/www/html/stuffandrewrites.com/public_html/wp-admin/plugins.php(192): plugin_sandbox_scrape() #2 {main} thrown in /mnt/volume01/www/html/stuffandrewrites.com/public_html/wp-content/plugins/bs-preloader-main/main.php on line 21

**Comment by crftwrk** [comment]
Hi Andre,

thank you for reporting. Which version are you using?

Bug came with update checker v5 in 5.1.1, but has been downgraded yesterday to v4 in 5.1.2. 

Please download and install latest 5.1.2 https://github.com/bootscore/bs-preloader/releases and let me know if this solves the error.

This affects bS Swiper and bS Grid plugins as well. If you are using one of this plugins, please let me know if there are issues as well.

Thanks 

Basti

**Comment by crftwrk** [comment]
Fixed by https://github.com/bootscore/bs-preloader/pull/16
