### ISSUE TITLE
Disable Fadeout when user use CTRL+Left click

### ISSUE THREAD

**Issue by ahmedlmahmoud** [bootscore/bs-preloader#2]
I needed to add this code to make page stop fading when I press CTRL + Left click.. I think you need to fix that too or a better solution
if (event.ctrlKey) {
            // ctrl + click is pressed
  }else{
  $("#preloader").fadeIn('slow');
  $("#status").fadeIn('slow');
}

**Comment by crftwrk** [comment]
👍 Good idea. Do you want to create a PR?

**Comment by crftwrk** [comment]
Fixed by https://github.com/bootscore/bs-preloader/releases/tag/5.0.1.0
