### ISSUE TITLE
Preloader does not work properly with page history

### ISSUE THREAD

**Issue by Kemal-Sulic** [bootscore/bs-preloader#6]
I created this issue to first discuss the fix I created. 

Would a pull request have been the more appropriate choice here?

First, the fix: 

`window.onpagehide = function() {
    $('#status').fadeOut('fast');
    $('#preloader').delay(350).fadeOut('slow');
};`

This code is compatible with the back/forward cache (bfcache) which is of course optimal.

Please help me now to understand if this is really the right solution. I myself have tested the fix throughout without giving the server the possibility to cache the page.

**Comment by crftwrk** [comment]
This prevents preloader stucking by press the browser back/forward buttons, correct? Tested it and works fine in my case, thank you.

I'm happy if you open a pull request.

**Comment by Kemal-Sulic** [comment]
Hey, I'm very sorry for the late reply but I'm not able to get to my desktop at the moment as my mom has been hospitalized and I'm with her. You can just use the code, would make me more than happy if you mention me.

Thank you.

**Comment by crftwrk** [comment]
Done, thank you. All the best for your mum.
