### ISSUE TITLE
Not preloading bs-swiper images

### ISSUE THREAD

**Issue by artinflight** [bootscore/bs-preloader#8]
I'm encountering an issue with bs-preloader and bs-swiper where the next images in queue on a hero slider do not pre-load, this causes a blank image to display on the first few slides. 

Hope there's an easy fix for this! Thanks in advance!

Sample: [artinflight.ca](https://artinflight.ca)

**Comment by crftwrk** [comment]
This has nothing to do with preloader or swiper plugin. Your server seems not to be the fastest one or is busy right now. 

Your images are also very big. This one https://artinflight.ca/wp-content/uploads/2018/11/d754373-edit-edit.jpg for example has a size of 2 MB. Reduce filesize and speed up loading by using https://tinypng.com.

Google Pagespeed says this:

![Bildschirmfoto 2022-03-28 um 19 59 52](https://user-images.githubusercontent.com/51531217/160458910-3d2853ff-391e-4bd3-ae22-bfb34a775d7a.png)

Does this help?

**Comment by artinflight** [comment]
Thank you, I will look into that. Is there a way to prevent the page from displaying until the images have pre-loaded?

**Comment by crftwrk** [comment]
> Is there a way to prevent the page from displaying until the images have pre-loaded?

No, preloader hides when html and scripts are completely loaded. But there should no problems with that. Just reduce filesize and it will work fine. As mentioned in my previous comment, Google says that you can save nearly 20 seconds loading time by using correct image formats and sizes. 

All good
